# Numpy

In [3]:
import numpy as np

## Exploring arrays in numpy

In [14]:
a = np.array([-5, -4, -3, -2, -1])

In [15]:
a

array([-5, -4, -3, -2, -1])

In [20]:
a[4]

-1

In [19]:
a[1:4]

array([-4, -3, -2])

In [21]:
a[::2]

array([-5, -3, -1])

In [11]:
b = np.array([1, 2, 3, 4, 5])

In [12]:
b[[0, 2, -1]]

array([1, 3, 5])

## Memory usage: Dtypes

In [22]:
a.dtype

dtype('int32')

In [102]:
c = np.array([5, 6, 7, 8, 9], dtype=np.int8)

In [26]:
c.dtype

dtype('int8')

## Dimensions

### 1 Dimension

In [29]:
c.ndim

1

In [79]:
c.size

5

### 2 Dimensions

In [89]:
D = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])

In [90]:
D.ndim

2

In [91]:
D.size

12

### 3 Dimensions

In [92]:
E = np.array(
    [
        [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]],
        [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]],
    ]
)

In [93]:
E.ndim

3

In [94]:
E.size

24

### 4 Dimensions

In [95]:
F = np.array(
    [
        [
            [[1, 2], [1, 2]],
            [[1, 2], [1, 2]],
        ],
        [
            [[1, 2], [1, 2]],
            [[1, 2], [1, 2]],
        ],
    ]
)

In [96]:
F.ndim

4

In [97]:
F.size

16

## Array functions

In [98]:
F.sum()

24

In [99]:
F.sum(axis=0)

array([[[2, 4],
        [2, 4]],

       [[2, 4],
        [2, 4]]])

In [100]:
F.var()

0.25

In [101]:
F.mean()

1.5

In [88]:
F.std()

0.5

...

## Vectorized operations

In [106]:
E + 10

array([[[11, 12, 13, 14],
        [11, 12, 13, 14],
        [11, 12, 13, 14]],

       [[11, 12, 13, 14],
        [11, 12, 13, 14],
        [11, 12, 13, 14]]])

In [107]:
E

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [108]:
E += 10

In [109]:
E

array([[[11, 12, 13, 14],
        [11, 12, 13, 14],
        [11, 12, 13, 14]],

       [[11, 12, 13, 14],
        [11, 12, 13, 14],
        [11, 12, 13, 14]]])

In [110]:
E > 12

array([[[False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True]],

       [[False, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True,  True]]])

In [111]:
E * 2

array([[[22, 24, 26, 28],
        [22, 24, 26, 28],
        [22, 24, 26, 28]],

       [[22, 24, 26, 28],
        [22, 24, 26, 28],
        [22, 24, 26, 28]]])

In [112]:
D

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [203]:
D2 = np.array([[2, 2, 2, 2], 
               [3, 3, 3, 3], 
               [5, 5, 5, 5]])

In [138]:
D * D2

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 5, 10, 15, 20]])

In [134]:
D3 = np.array([2, 3, 3, 5])

In [122]:
D * D3

array([[ 2,  6,  9, 20],
       [ 2,  6,  9, 20],
       [ 2,  6,  9, 20]])

In [146]:
D4 = np.array([[2], 
               [3], 
               [5]])

In [147]:
D * D

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16],
       [ 1,  4,  9, 16]])

## Matrix multiplication

In [148]:
np.dot(D, D3)

array([37, 37, 37])

In [164]:
X = [[1, 2, 3], [4, 5, 6]]
Y = [[7, 8], [9, 10], [11, 12]]
np.dot(X, Y)

array([[ 58,  64],
       [139, 154]])

In [165]:
U = [[1, 2, 3]]
V = [[7], 
     [8], 
     [9]]
np.dot(U, V)

array([[50]])

In [166]:
np.dot(V, U)

array([[ 7, 14, 21],
       [ 8, 16, 24],
       [ 9, 18, 27]])

## Matrix division

In [204]:
R = np.array([[5, 4, 2], 
              [2, 3, 5], 
              [1, -2, 5]])

In [205]:
T = np.array([[7, 5, -1], 
              [-2, 0, 1], 
              [1, -1, 0]])

In [206]:
np.linalg.inv(T)

array([[ 0.1,  0.1,  0.5],
       [ 0.1,  0.1, -0.5],
       [ 0.2,  1.2,  1. ]])

In [207]:
np.dot(R, np.linalg.inv(T))

array([[1.3, 3.3, 2.5],
       [1.5, 6.5, 4.5],
       [0.9, 5.9, 6.5]])

## Transposition

In [208]:
D

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [209]:
D.T

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

## Performance of NumPy vs regular Python

In [221]:
m = list(range(100000))

In [228]:
n = np.arange(100000, dtype=np.intp)

In [229]:
%time sum([x ** 2 for x in m])

Wall time: 27.9 ms


333328333350000

In [254]:
%time np.sum(n ** 2)

Wall time: 998 µs


333328333350000