# Numpy

## Exploring arrays in numpy

In [38]:
import sys
import numpy as np

In [14]:
a = np.array([-5, -4, -3, -2, -1])

In [15]:
a

array([-5, -4, -3, -2, -1])

In [20]:
a[4]

-1

In [19]:
a[1:4]

array([-4, -3, -2])

In [21]:
a[::2]

array([-5, -3, -1])

In [11]:
b = np.array([1, 2, 3, 4, 5])

In [12]:
b[[0, 2, -1]]

array([1, 3, 5])

## Memory usage: Dtypes

In [22]:
a.dtype

dtype('int32')

In [24]:
c = np.array([5, 6, 7, 8, 9], dtype=np.int8)

In [26]:
c.dtype

dtype('int8')

## Dimensions

### 1 Dimension

In [29]:
c.ndim

1

### 2 Dimensions

In [27]:
d = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])

In [28]:
d.ndim

2

### 3 Dimensions

In [36]:
e = np.array(
    [
        [[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]],
        [[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]],
    ]
)

In [37]:
e.ndim

3